<a href="https://colab.research.google.com/github/Ricardomanuel1/Maestria_Ciencia_de_Datos/blob/main/Informe_Operacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
#librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import csv
from pandas.io import excel
import zipfile
import plotly.express as px
import statsmodels.api as sm
import warnings
warnings.filterwarnings('ignore')
import time
from matplotlib import style
plt.rcParams['image.cmap'] = "bwr"
#plt.rcParams['figure.dpi'] = "100"
plt.rcParams['savefig.bbox'] = "tight"
style.use('ggplot') or plt.style.use('ggplot')

In [25]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [41]:
ruta="/content/drive/MyDrive/INFORME DE OPERACION STN/OneDrive_2023-09-22.zip"

In [42]:
with zipfile.ZipFile(ruta_zip, "r") as archivo_zip:
    # Extraer todos los archivos del ZIP
    archivo_zip.extractall()

    # Listar los archivos contenidos en el ZIP
    lista_archivos = archivo_zip.namelist()
    print("Archivos contenidos en el ZIP:", lista_archivos)

Archivos contenidos en el ZIP: ['DT NORTE/IDO - CARHUAQUERO (ISAP).xlsm', 'DT NORTE/IDO - CHICLAYO OESTE (REP).xlsm', 'DT NORTE/IDO - CHIMBOTE 1 (REP).xlsm', 'DT NORTE/IDO - CHIMBOTE NUEVA (CTM).xlsm', 'DT NORTE/IDO - GUADALUPE (REP).xlsm', 'DT NORTE/IDO - HUALLANCA (ISAP).xlsm', 'DT NORTE/IDO - LA BREA (CTM).xlsm', 'DT NORTE/IDO - LAGUNA LA NIÑA (CTM).xlsm', 'DT NORTE/IDO - PARAMONGA NUEVA (REP).xlsm', 'DT NORTE/IDO - PARIÑAS (REP).xlsm', 'DT NORTE/IDO - PIURA OESTE (REP).xlsm', 'DT NORTE/IDO - REQUE (REP).xlsm', 'DT NORTE/IDO - TALARA (REP).xlsm', 'DT NORTE/IDO - TRUJILLO NORTE (REP).xlsm', 'DT NORTE/IDO - TRUJILLO NUEVA (CTM).xlsm', 'DT NORTE/IDO - VIZCARRA (ISAP).xlsm', 'DT NORTE/IDO - ZORRITOS (REP).xlsm']

In [43]:
lista_archivos

['DT NORTE/IDO - CARHUAQUERO (ISAP).xlsm',
 'DT NORTE/IDO - CHICLAYO OESTE (REP).xlsm',
 'DT NORTE/IDO - CHIMBOTE 1 (REP).xlsm',
 'DT NORTE/IDO - CHIMBOTE NUEVA (CTM).xlsm',
 'DT NORTE/IDO - GUADALUPE (REP).xlsm',
 'DT NORTE/IDO - HUALLANCA (ISAP).xlsm',
 'DT NORTE/IDO - LA BREA (CTM).xlsm',
 'DT NORTE/IDO - LAGUNA LA NIÑA (CTM).xlsm',
 'DT NORTE/IDO - PARAMONGA NUEVA (REP).xlsm',
 'DT NORTE/IDO - PARIÑAS (REP).xlsm',
 'DT NORTE/IDO - PIURA OESTE (REP).xlsm',
 'DT NORTE/IDO - REQUE (REP).xlsm',
 'DT NORTE/IDO - TALARA (REP).xlsm',
 'DT NORTE/IDO - TRUJILLO NORTE (REP).xlsm',
 'DT NORTE/IDO - TRUJILLO NUEVA (CTM).xlsm',
 'DT NORTE/IDO - VIZCARRA (ISAP).xlsm',
 'DT NORTE/IDO - ZORRITOS (REP).xlsm']

In [49]:
CARHUAQUERO=pd.read_excel('DT NORTE/IDO - CARHUAQUERO (ISAP).xlsm')
CHICLAYO=pd.read_excel('DT NORTE/IDO - CHICLAYO OESTE (REP).xlsm')
CHIM1=pd.read_excel('DT NORTE/IDO - CHIMBOTE 1 (REP).xlsm')
CHMB=pd.read_excel('DT NORTE/IDO - CHIMBOTE NUEVA (CTM).xlsm')
GUADALUPE=pd.read_excel('DT NORTE/IDO - HUALLANCA (ISAP).xlsm')
HUALLANCA=pd.read_excel('DT NORTE/IDO - HUALLANCA (ISAP).xlsm')
BREA=pd.read_excel('DT NORTE/IDO - LA BREA (CTM).xlsm')
NIÑA=pd.read_excel('DT NORTE/IDO - LAGUNA LA NIÑA (CTM).xlsm')
PARAMONGA=pd.read_excel('DT NORTE/IDO - PARAMONGA NUEVA (REP).xlsm')
PARIÑAS=pd.read_excel('DT NORTE/IDO - PARIÑAS (REP).xlsm')
PIURA =pd.read_excel('DT NORTE/IDO - PIURA OESTE (REP).xlsm')
REQUE=pd.read_excel('DT NORTE/IDO - REQUE (REP).xlsm')
TALARA=pd.read_excel('DT NORTE/IDO - TALARA (REP).xlsm')
TRUJILLO_NORTE=pd.read_excel('DT NORTE/IDO - TRUJILLO NORTE (REP).xlsm')
TRUJILLO_NUEVA=pd.read_excel( 'DT NORTE/IDO - TRUJILLO NUEVA (CTM).xlsm')
VIZCARRA=pd.read_excel('DT NORTE/IDO - VIZCARRA (ISAP).xlsm')
ZORRITOS=pd.read_excel('DT NORTE/IDO - ZORRITOS (REP).xlsm')

In [48]:
CARHUAQUERO

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,X,Unnamed: 5,Unnamed: 6
0,NaN,SUBESTACIÓN,NUMERO DE PERMISO,FECHA DE FIN,HORA DE FIN,¿SE CONCLUYÓ CON EL TRABAJO?,OBSERVACIONES
1,NaN,CARHUAQUERO (ISAP),52,2023-08-13 00:00:00,08:12:02,SI,NINGUNA
2,NaN,CARHUAQUERO (ISAP),51,2023-08-11 00:00:00,18:56:22,SI,ACTIVIDAD CULMINADA
3,NaN,CARHUAQUERO (ISAP),50,2023-08-10 00:00:00,16:40:37.480000,NO,SE CONTINUA MAÑANA
4,NaN,CARHUAQUERO (ISAP),49,2023-08-09 00:00:00,17:00:59,NO,CONTINUAN MAÑANA
5,NaN,CARHUAQUERO (ISAP),47,2023-08-08 00:00:00,11:58:00,SI,NINGUNA
6,NaN,CARHUAQUERO (ISAP),46,2023-08-08 00:00:00,12:40:00,SI,NINGUNA
7,NaN,CARHUAQUERO (ISAP),45,2023-08-07 00:00:00,13:02:00,NO,CONTINUAN
8,NaN,CARHUAQUERO (ISAP),44,2023-08-05 00:00:00,12:45:00,SI,NINGUNA
9,NaN,CARHUAQUERO (ISAP),43,2023-08-05 00:00:00,12:45:00,SI,NINGUNA
10,NaN,CARHUAQUERO (ISAP),42,2023-08-05 00:00:00,15:00:00,SI,NINGUNA
11,NaN,CARHUAQUERO (ISAP),41,2023-08-04 00:00:00,14:00:00,SI,NINGUNA
12,NaN,CARHUAQUERO (ISAP),40,2023-08-04 00:00:00,13:30:00,SI,NINGUNA
13,NaN,CARHUAQUERO (ISAP),39,2023-08-04 00:00:00,13:30:00,SI,NINGUNA
14,NaN,CARHUAQUERO (ISAP),38,2023-08-04 00:00:00,13:30:00,SI,NINGUNA
15,NaN,CARHUAQUERO (ISAP),37,NaN,NaN,NaN,NaN
16,NaN,CARHUAQUERO (ISAP),36,NaN,NaN,NaN,NaN
17,NaN,CARHUAQUERO (ISAP),35,NaN,NaN,NaN,NaN
18,NaN,CARHUAQUERO (ISAP),34,NaN,NaN,NaN,NaN
19,NaN,CARHUAQUERO (ISAP),33,NaN,NaN,NaN,NaN
20,NaN,CARHUAQUERO (ISAP),32,NaN,NaN,NaN,NaN
21,NaN,CARHUAQUERO (ISAP),31,NaN,NaN,NaN,NaN
22,NaN,CARHUAQUERO (ISAP),30,2023-06-17 00:00:00,14:20:00,NaN,NaN
23,NaN,CARHUAQUERO (ISAP),29,2023-06-12 00:00:00,13:00:00,NaN,NaN
24,NaN,CARHUAQUERO (ISAP),28,2023-06-09 00:00:00,16:40:00,NaN,NaN
25,NaN,CARHUAQUERO (ISAP),27,2023-06-08 00:00:00,16:45:00,NaN,NaN
26,NaN,CARHUAQUERO (ISAP),26,2023-06-07 00:00:00,16:45:00,NaN,NaN
27,NaN,CARHUAQUERO (ISAP),25,2023-06-06 00:00:00,16:45:00,NaN,NaN
28,NaN,CARHUAQUERO (ISAP),24,2023-05-05 00:00:00,16:43:00,NaN,NaN
29,NaN,CARHUAQUERO (ISAP),23,2023-06-05 00:00:00,16:50:00,NaN,NaN
30,NaN,CARHUAQUERO (ISAP),22,2023-06-01 00:00:00,13:50:00,NaN,NaN
31,NaN,CARHUAQUERO (ISAP),21,2023-05-24 00:00:00,12:15:00,NaN,NaN
32,NaN,CARHUAQUERO (ISAP),20,2023-05-18 00:00:00,15:00:00,NaN,NaN
33,NaN,CARHUAQUERO (ISAP),19,2023-05-17 00:00:00,16:55:00,NaN,NaN
34,NaN,CARHUAQUERO (ISAP),18,2023-05-05 00:00:00,13:00:00,NaN,NaN
35,NaN,CARHUAQUERO (ISAP),17,2023-05-04 00:00:00,19:20:00,NaN,NaN
36,NaN,CARHUAQUERO (ISAP),16,2023-05-03 00:00:00,16:00:00,NaN,NaN
37,NaN,CARHUAQUERO (ISAP),15,205/2023,15:52:00,NaN,NaN
38,NaN,CARHUAQUERO (ISAP),14,2023-04-13 00:00:00,12:00:00,NaN,NaN
39,NaN,CARHUAQUERO (ISAP),13,2023-04-11 00:00:00,15:50:00,NaN,NaN
40,NaN,CARHUAQUERO (ISAP),12,2023-02-17 00:00:00,17:30:00,NaN,NaN
41,NaN,CARHUAQUERO (ISAP),11,2023-02-17 00:00:00,17:30:00,NaN,NaN
42,NaN,CARHUAQUERO (ISAP),10,2023-02-16 00:00:00,17:15:00,NaN,NaN
43,NaN,CARHUAQUERO (ISAP),9,2023-02-15 00:00:00,15:00:00,NaN,NaN
44,NaN,CARHUAQUERO (ISAP),8,2023-02-01 00:00:00,15:20:00,NaN,NaN
45,NaN,CARHUAQUERO (ISAP),7,2023-01-29 00:00:00,16:15:00,NaN,NaN
46,NaN,CARHUAQUERO (ISAP),6,2023-01-29 00:00:00,16:40:00,NaN,NaN
47,NaN,CARHUAQUERO (ISAP),5,2023-01-29 00:00:00,16:45:00,NaN,NaN
48,NaN,CARHUAQUERO (ISAP),4,2023-01-29 00:00:00,16:20:00,NaN,NaN
49,NaN,CARHUAQUERO (ISAP),3,2023-01-29 00:00:00,13:35:00,NaN,NaN
50,NaN,CARHUAQUERO (ISAP),2,2023-01-24 00:00:00,17:15:00,NaN,NaN
51,NaN,CARHUAQUERO (ISAP),1,2023-01-21 00:00:00,17:00:00,NaN,NaN

In [33]:
df1=df[0:]

In [34]:
df1

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,ANA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NUMERO DE PERMISO,SUBESTACIÓN,FECHA DE INICIO,HORA DE INICIO,PLAN DE TRABAJO,TIPO DE PLAN,INTEGRADOR,PLANES DE TRABAJO DEPENDIENTES,AUTORIZACIÓN CCREP,...,EMPRESA,PROPIETARIO DEL ACTIVO,SUPERVISOR DE TRABAJO,SUPERVISOR SUSTITUTO,NUMERO DE TRABAJADORES,ASISTENTE / INGENIERO DE TURNO,FECHA DE FIN,HORA DE FIN2,¿SE CONCLUYÓ CON EL TRABAJO?,OBSERVACIONES
2,NaN,409,CHIMBOTE 1 (REP),2023-09-21 00:00:00,07:50:19,R0095946,SIN CONSIGNACIÓN,NaN,NaN,NaN,...,MOREEL,ISAPERU,HERNAN REFOJES,NaN,5,RQUISPE,Permiso abierto,Permiso abierto,Permiso abierto,Permiso abierto
3,NaN,408,CHIMBOTE 1 (REP),2023-09-21 00:00:00,07:49:16,R0095945,SIN CONSIGNACIÓN,NaN,NaN,NaN,...,MOREEL,ISAPERU,HERNAN REFOJES,NaN,5,RQUISPE,Permiso abierto,Permiso abierto,Permiso abierto,Permiso abierto
4,NaN,407,CHIMBOTE 1 (REP),2023-09-20 00:00:00,09:30:39,INTERNO,NaN,NaN,NaN,NaN,...,UNION ELECTRICA,INTERNEXA,ELIFIO LEYVA,NaN,1,RQUISPE,2023-09-20 00:00:00,16:30:47,SI,LA ACTIVIDAD FUE EN EL TABLERO DE INTERNEXA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,NaN,5,CHIMBOTE 1 (REP),2023-01-05 00:00:00,07:38:36.470000,R0095471,SIN CONSIGNACIÓN,NO,NaN,NO,...,VyT,REP,BRANDY INGARUCA,MODESTO REYES,5,DMARROQUIN,2023-01-05 00:00:00,15:59:27,NO,CONTINÚAN MAÑANA
408,NaN,4,CHIMBOTE 1 (REP),2023-01-04 00:00:00,08:10:55,R0097233,SIN CONSIGNACIÓN,NO,NaN,NO,...,VyT,REP,ALDO LLUCHO,DANIEL FERNANDEZ,4,DMARROQUIN,2023-01-04 00:00:00,16:00:55,NO,CONTINÚAN MAÑANA
409,NaN,3,CHIMBOTE 1 (REP),2023-01-04 00:00:00,07:54:03.590000,R0095471,SIN CONSIGNACIÓN,NO,NaN,NO,...,VyT,REP,BRANDY INGARUCA,MODESTO REYES,10,DMARROQUIN,2023-01-04 00:00:00,15:50:06,NO,CONTINÚAN MAÑANA
410,NaN,2,CHIMBOTE 1 (REP),2023-01-03 00:00:00,08:30:34,R0095471,SIN CONSIGNACIÓN,NO,NaN,NO,...,VyT,REP,BRANDY INGARUCA,MODESTO REYES,10,DMARROQUIN,2023-01-03 00:00:00,15:54:52,NO,CONTINÚAN MAÑANA
411,NaN,1,CHIMBOTE 1 (REP),2023-01-03 00:00:00,08:20:55,R0097233,SIN CONSIGNACIÓN,NO,NaN,NO,...,VyT,REP,ALDO LLUCHO,DANIEL FERNANDEZ,4,DMARROQUIN,2023-01-03 00:00:00,16:15:49,NO,CONTINÚAN MAÑANA

In [27]:
df2=df1.drop([0,4,7,8,9,10,14,15,19,22,23,24,25], axis=1)

In [28]:
df2[6].unique()

array(['TIPO DE PLAN', 'SIN CONSIGNACIÓN', nan, 'LOCAL', 'NACIONAL'],
      dtype=object)

In [29]:
df2

,1,2,3,5,6,11,12,13,16,17,18,20,21
1,NUMERO DE PERMISO,SUBESTACIÓN,FECHA DE INICIO,PLAN DE TRABAJO,TIPO DE PLAN,ACTIVIDAD,EQUIPO / LLTT,ESTRUCTURAS,EMPRESA,PROPIETARIO DEL ACTIVO,SUPERVISOR DE TRABAJO,NUMERO DE TRABAJADORES,ASISTENTE / INGENIERO DE TURNO
2,409,CHIMBOTE 1 (REP),2023-09-21 00:00:00,R0095946,SIN CONSIGNACIÓN,CORTE DE VEGETACION L1105,L1105HUACHIM-ISAP,"P127,P107,P108,P174",MOREEL,ISAPERU,HERNAN REFOJES,5,RQUISPE
3,408,CHIMBOTE 1 (REP),2023-09-21 00:00:00,R0095945,SIN CONSIGNACIÓN,CORTE DE VEGETACION L1103,L1103HUACHIM-ISAP,P115-P164,MOREEL,ISAPERU,HERNAN REFOJES,5,RQUISPE
4,407,CHIMBOTE 1 (REP),2023-09-20 00:00:00,INTERNO,NaN,MANTENIMIENTO A LOS TABLEROS DE INTERNEXA,CHIM,NaN,UNION ELECTRICA,INTERNEXA,ELIFIO LEYVA,1,RQUISPE
5,406,CHIMBOTE 1 (REP),2023-09-20 00:00:00,INTERNO,NaN,EXTRAER LA IMAGEN DE LA PC REGO,CHIM,NaN,TECNO GOLBAL,NaN,JOSE ZUÑIGA,1,RQUISPE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,5,CHIMBOTE 1 (REP),2023-01-05 00:00:00,R0095471,SIN CONSIGNACIÓN,MP 1A INSPECCION LIGERA,L2232CHITRUJ,P128 - P159,VyT,REP,BRANDY INGARUCA,5,DMARROQUIN
408,4,CHIMBOTE 1 (REP),2023-01-04 00:00:00,R0097233,SIN CONSIGNACIÓN,REPARACIÓN TUBERÍA AGUA,CHIM,NaN,VyT,REP,ALDO LLUCHO,4,DMARROQUIN
409,3,CHIMBOTE 1 (REP),2023-01-04 00:00:00,R0095471,SIN CONSIGNACIÓN,MP 1A INSPECCION LIGERA,L2232CHITRUJ,P65 - P128,VyT,REP,BRANDY INGARUCA,10,DMARROQUIN
410,2,CHIMBOTE 1 (REP),2023-01-03 00:00:00,R0095471,SIN CONSIGNACIÓN,MP 1A INSPECCION LIGERA,L2232CHITRUJ,P1 - P64,VyT,REP,BRANDY INGARUCA,10,DMARROQUIN
411,1,CHIMBOTE 1 (REP),2023-01-03 00:00:00,R0097233,SIN CONSIGNACIÓN,REPARACIÓN TUBERÍA AGUA,CHIM,NaN,VyT,REP,ALDO LLUCHO,4,DMARROQUIN

In [8]:
df2.columns

Int64Index([1, 2, 3, 5, 6, 11, 12, 13, 16, 17, 18, 20, 21], dtype='int64')

In [9]:
df2.dtypes

1     object
2     object
3     object
5     object
6     object
11    object
12    object
13    object
16    object
17    object
18    object
20    object
21    object
dtype: object

In [10]:
df2[(df2[6]=="TIPO DE PLAN") | (df2[6]=="SIN CONSIGNACIÓN") | (df2[6]=="LOCAL") | (df2[6]=="NACIONAL")]

,1,2,3,5,6,11,12,13,16,17,18,20,21
1,NUMERO DE PERMISO,SUBESTACIÓN,FECHA DE INICIO,PLAN DE TRABAJO,TIPO DE PLAN,ACTIVIDAD,EQUIPO / LLTT,ESTRUCTURAS,EMPRESA,PROPIETARIO DEL ACTIVO,SUPERVISOR DE TRABAJO,NUMERO DE TRABAJADORES,ASISTENTE / INGENIERO DE TURNO
2,409,CHIMBOTE 1 (REP),2023-09-21 00:00:00,R0095946,SIN CONSIGNACIÓN,CORTE DE VEGETACION L1105,L1105HUACHIM-ISAP,"P127,P107,P108,P174",MOREEL,ISAPERU,HERNAN REFOJES,5,RQUISPE
3,408,CHIMBOTE 1 (REP),2023-09-21 00:00:00,R0095945,SIN CONSIGNACIÓN,CORTE DE VEGETACION L1103,L1103HUACHIM-ISAP,P115-P164,MOREEL,ISAPERU,HERNAN REFOJES,5,RQUISPE
6,405,CHIMBOTE 1 (REP),2023-09-20 00:00:00,R0102118,LOCAL,REVISION DE ONDA PORTADORA_CIERRE DE LINK DE L...,CHIM138L1104,NaN,REP,ISAPERU,CARLOS CERNA,2,RQUISPE
7,404,CHIMBOTE 1 (REP),2023-09-20 00:00:00,R0095946,SIN CONSIGNACIÓN,CORTE DE VEGETACION L1105,L1105HUACHIM-ISAP,P174-197,MOREEL,ISAPERU,HERNAN REFOJES,5,RQUISPE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,5,CHIMBOTE 1 (REP),2023-01-05 00:00:00,R0095471,SIN CONSIGNACIÓN,MP 1A INSPECCION LIGERA,L2232CHITRUJ,P128 - P159,VyT,REP,BRANDY INGARUCA,5,DMARROQUIN
408,4,CHIMBOTE 1 (REP),2023-01-04 00:00:00,R0097233,SIN CONSIGNACIÓN,REPARACIÓN TUBERÍA AGUA,CHIM,NaN,VyT,REP,ALDO LLUCHO,4,DMARROQUIN
409,3,CHIMBOTE 1 (REP),2023-01-04 00:00:00,R0095471,SIN CONSIGNACIÓN,MP 1A INSPECCION LIGERA,L2232CHITRUJ,P65 - P128,VyT,REP,BRANDY INGARUCA,10,DMARROQUIN
410,2,CHIMBOTE 1 (REP),2023-01-03 00:00:00,R0095471,SIN CONSIGNACIÓN,MP 1A INSPECCION LIGERA,L2232CHITRUJ,P1 - P64,VyT,REP,BRANDY INGARUCA,10,DMARROQUIN
411,1,CHIMBOTE 1 (REP),2023-01-03 00:00:00,R0097233,SIN CONSIGNACIÓN,REPARACIÓN TUBERÍA AGUA,CHIM,NaN,VyT,REP,ALDO LLUCHO,4,DMARROQUIN

In [170]:
df2

,1,2,3,5,6,11,12,13,16,17,18,20,21
1,NUMERO DE PERMISO,SUBESTACIÓN,FECHA DE INICIO,PLAN DE TRABAJO,TIPO DE PLAN,ACTIVIDAD,EQUIPO / LLTT,ESTRUCTURAS,EMPRESA,PROPIETARIO DEL ACTIVO,SUPERVISOR DE TRABAJO,NUMERO DE TRABAJADORES,ASISTENTE / INGENIERO DE TURNO
2,409,CHIMBOTE 1 (REP),2023-09-21 00:00:00,R0095946,SIN CONSIGNACIÓN,CORTE DE VEGETACION L1105,L1105HUACHIM-ISAP,"P127,P107,P108,P174",MOREEL,ISAPERU,HERNAN REFOJES,5,RQUISPE
3,408,CHIMBOTE 1 (REP),2023-09-21 00:00:00,R0095945,SIN CONSIGNACIÓN,CORTE DE VEGETACION L1103,L1103HUACHIM-ISAP,P115-P164,MOREEL,ISAPERU,HERNAN REFOJES,5,RQUISPE
4,407,CHIMBOTE 1 (REP),2023-09-20 00:00:00,INTERNO,NaN,MANTENIMIENTO A LOS TABLEROS DE INTERNEXA,CHIM,NaN,UNION ELECTRICA,INTERNEXA,ELIFIO LEYVA,1,RQUISPE
5,406,CHIMBOTE 1 (REP),2023-09-20 00:00:00,INTERNO,NaN,EXTRAER LA IMAGEN DE LA PC REGO,CHIM,NaN,TECNO GOLBAL,NaN,JOSE ZUÑIGA,1,RQUISPE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,5,CHIMBOTE 1 (REP),2023-01-05 00:00:00,R0095471,SIN CONSIGNACIÓN,MP 1A INSPECCION LIGERA,L2232CHITRUJ,P128 - P159,VyT,REP,BRANDY INGARUCA,5,DMARROQUIN
408,4,CHIMBOTE 1 (REP),2023-01-04 00:00:00,R0097233,SIN CONSIGNACIÓN,REPARACIÓN TUBERÍA AGUA,CHIM,NaN,VyT,REP,ALDO LLUCHO,4,DMARROQUIN
409,3,CHIMBOTE 1 (REP),2023-01-04 00:00:00,R0095471,SIN CONSIGNACIÓN,MP 1A INSPECCION LIGERA,L2232CHITRUJ,P65 - P128,VyT,REP,BRANDY INGARUCA,10,DMARROQUIN
410,2,CHIMBOTE 1 (REP),2023-01-03 00:00:00,R0095471,SIN CONSIGNACIÓN,MP 1A INSPECCION LIGERA,L2232CHITRUJ,P1 - P64,VyT,REP,BRANDY INGARUCA,10,DMARROQUIN
411,1,CHIMBOTE 1 (REP),2023-01-03 00:00:00,R0097233,SIN CONSIGNACIÓN,REPARACIÓN TUBERÍA AGUA,CHIM,NaN,VyT,REP,ALDO LLUCHO,4,DMARROQUIN

(412, 26)

In [ ]:
df_final=df.drop(['ANA'],axis=1)

In [ ]:
df_final.head(4)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 16,Unnamed: 17,,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,NUMERO DE PERMISO,SUBESTACIÓN,FECHA DE INICIO,HORA DE INICIO,PLAN DE TRABAJO,TIPO DE PLAN,INTEGRADOR,PLANES DE TRABAJO DEPENDIENTES,AUTORIZACIÓN CCREP,O.M.,...,EMPRESA,PROPIETARIO DEL ACTIVO,SUPERVISOR DE TRABAJO,SUPERVISOR SUSTITUTO,NUMERO DE TRABAJADORES,ASISTENTE / INGENIERO DE TURNO,FECHA DE FIN,HORA DE FIN2,¿SE CONCLUYÓ CON EL TRABAJO?,OBSERVACIONES
1,347,CHIMBOTE 1 (REP),2023-08-11 00:00:00,08:30:00,R0101219,LOCAL,NaN,NaN,SI,503591,...,REP,REP,CCERNA,NaN,2,CCERNA,Permiso abierto,Permiso abierto,Permiso abierto,Permiso abierto
2,346,CHIMBOTE 1 (REP),2023-08-10 00:00:00,15:23:09.060000,R0101231,SIN CONSIGNACIÓN,NaN,NaN,NO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Permiso abierto,Permiso abierto,Permiso abierto,Permiso abierto
3,345,CHIMBOTE 1 (REP),2023-08-10 00:00:00,08:34:13.610000,R0100077,LOCAL,NaN,NaN,SI,NaN,...,UNION ELECTRICA,REP,WILSON LIÑAN,ELIU RIVERA,3,CCERNA,2023-08-10 00:00:00,16:46:22.060000,NO,CONTINÚAN MAÑANA

In [ ]:
df_final[['Unnamed: 5']]

          Unnamed: 5
0    PLAN DE TRABAJO
1           R0101219
2           R0101231
3           R0100077
4           R0100077
..               ...
344         R0095471
345         R0097233
346         R0095471
347         R0095471
348         R0097233

[349 rows x 1 columns]

In [ ]:
df.shape

(349, 26)

In [ ]:
df[0:3]

,ANA,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,NaN,NUMERO DE PERMISO,SUBESTACIÓN,FECHA DE INICIO,HORA DE INICIO,PLAN DE TRABAJO,TIPO DE PLAN,INTEGRADOR,PLANES DE TRABAJO DEPENDIENTES,AUTORIZACIÓN CCREP,...,EMPRESA,PROPIETARIO DEL ACTIVO,SUPERVISOR DE TRABAJO,SUPERVISOR SUSTITUTO,NUMERO DE TRABAJADORES,ASISTENTE / INGENIERO DE TURNO,FECHA DE FIN,HORA DE FIN2,¿SE CONCLUYÓ CON EL TRABAJO?,OBSERVACIONES
1,NaN,347,CHIMBOTE 1 (REP),2023-08-11 00:00:00,08:30:00,R0101219,LOCAL,NaN,NaN,SI,...,REP,REP,CCERNA,NaN,2,CCERNA,Permiso abierto,Permiso abierto,Permiso abierto,Permiso abierto
2,NaN,346,CHIMBOTE 1 (REP),2023-08-10 00:00:00,15:23:09.060000,R0101231,SIN CONSIGNACIÓN,NaN,NaN,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,Permiso abierto,Permiso abierto,Permiso abierto,Permiso abierto

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import csv
import zipfile
import plotly.express as px
import statsmodels.api as sm
import warnings
warnings.filterwarnings('ignore')
import time
from matplotlib import style
import openpyxl

In [ ]:

ruta_zip='/content/OneDrive_2023-08-11.zip'

In [ ]:
# Abrir el archivo ZIP en modo lectura
with zipfile.ZipFile(ruta_zip, "r") as archivo_zip:
    # Extraer todos los archivos del ZIP
    archivo_zip.extractall()

In [ ]:
# Listar los archivos contenidos en el ZIP - almacenamos lista de archivos en una variable
lista_archivos = archivo_zip.namelist()
print("Archivos contenidos en el ZIP:", lista_archivos)

Archivos contenidos en el ZIP: ['DT NORTE/IDO - CARHUAQUERO (ISAP).xlsm', 'DT NORTE/IDO - CHICLAYO OESTE (REP).xlsm', 'DT NORTE/IDO - CHIMBOTE 1 (REP).xlsm', 'DT NORTE/IDO - CHIMBOTE NUEVA (CTM).xlsm', 'DT NORTE/IDO - GUADALUPE (REP).xlsm', 'DT NORTE/IDO - HUALLANCA (ISAP).xlsm', 'DT NORTE/IDO - LA BREA (CTM).xlsm', 'DT NORTE/IDO - LAGUNA LA NIÑA (CTM).xlsm', 'DT NORTE/IDO - PARAMONGA NUEVA (REP).xlsm', 'DT NORTE/IDO - PARIÑAS (REP).xlsm', 'DT NORTE/IDO - PIURA OESTE (REP).xlsm', 'DT NORTE/IDO - REQUE (REP).xlsm', 'DT NORTE/IDO - TALARA (REP).xlsm', 'DT NORTE/IDO - TRUJILLO NORTE (REP).xlsm', 'DT NORTE/IDO - TRUJILLO NUEVA (CTM).xlsm', 'DT NORTE/IDO - VIZCARRA (ISAP).xlsm', 'DT NORTE/IDO - ZORRITOS (REP).xlsm']

In [ ]:
lista_archivos

['DT NORTE/IDO - CARHUAQUERO (ISAP).xlsm',
 'DT NORTE/IDO - CHICLAYO OESTE (REP).xlsm',
 'DT NORTE/IDO - CHIMBOTE 1 (REP).xlsm',
 'DT NORTE/IDO - CHIMBOTE NUEVA (CTM).xlsm',
 'DT NORTE/IDO - GUADALUPE (REP).xlsm',
 'DT NORTE/IDO - HUALLANCA (ISAP).xlsm',
 'DT NORTE/IDO - LA BREA (CTM).xlsm',
 'DT NORTE/IDO - LAGUNA LA NIÑA (CTM).xlsm',
 'DT NORTE/IDO - PARAMONGA NUEVA (REP).xlsm',
 'DT NORTE/IDO - PARIÑAS (REP).xlsm',
 'DT NORTE/IDO - PIURA OESTE (REP).xlsm',
 'DT NORTE/IDO - REQUE (REP).xlsm',
 'DT NORTE/IDO - TALARA (REP).xlsm',
 'DT NORTE/IDO - TRUJILLO NORTE (REP).xlsm',
 'DT NORTE/IDO - TRUJILLO NUEVA (CTM).xlsm',
 'DT NORTE/IDO - VIZCARRA (ISAP).xlsm',
 'DT NORTE/IDO - ZORRITOS (REP).xlsm']

In [ ]:
# Guardar los enlaces en un archivo CSV
with open("enlaces.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Enlace"])
    writer.writerows([[enlace] for enlace in lista_archivos])

print("Enlaces exportados correctamente a enlaces.csv.")

Enlaces exportados correctamente a enlaces.csv.

In [ ]:
# Leer los enlaces desde el archivo CSV
enlaces_df = pd.read_csv("enlaces.csv")

In [ ]:
# Crear una lista para almacenar los DataFrames de cada enlace
dfs = []

# Iterar sobre los enlaces y leer cada archivo CSV
for enlace in enlaces_df["Enlace"]:
    df = pd.read_csv(enlace, sep=';', encoding='unicode_escape')
    dfs.append(df)

# Concatenar los DataFrames en uno solo
df_final = pd.concat(dfs)

# Realizar cualquier procesamiento adicional con el DataFrame df_final

# Mostrar el DataFrame final
df_final

UnicodeDecodeError: ignored

In [ ]:
list1=[]
for i in range(1,11):
  list1.append(i)
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
[x for x in range(1,11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
sum1_100=sum([x for x in range(101)])
sum1_100

5050